CREATE DATABASE IF NOT EXISTS codigopostal_manoelbarata
CHARACTER SET utf8 COLLATE utf8_general_ci;

USE codigopostal_manoelbarata;

CREATE TABLE codigopostal (
    DD          VARCHAR(255) NOT NULL,
    CC          VARCHAR(255) NOT NULL,
    LLLL        VARCHAR(255) NOT NULL,
    LOCALIDADE  VARCHAR(255) NOT NULL,
    ART_COD     VARCHAR(255) NULL,
    ART_TIPO    VARCHAR(255) NULL,
    PRI_PREP    VARCHAR(255) NULL,
    ART_TITULO  VARCHAR(255) NULL,
    SEG_PREP    VARCHAR(255) NULL,
    ART_DESIG   VARCHAR(255) NULL,
    ART_LOCAL   VARCHAR(255) NULL,
    TROÇO       VARCHAR(255) NULL,
    PORTA       VARCHAR(255) NULL,
    CLIENTE     VARCHAR(255) NULL,
    CP4         VARCHAR(4)   NOT NULL,
    CP3         VARCHAR(255) NOT NULL,
    CPALF       VARCHAR(255) NOT NULL
);

CREATE TABLE distritos (
    DD      VARCHAR(255) NOT NULL,
    DESIG   VARCHAR(255) NOT NULL
);

CREATE TABLE concelhos (
    DD      VARCHAR(255) NOT NULL,
    CC      VARCHAR(255) NOT NULL,
    DESIG   VARCHAR(255) NOT NULL
);