
package projetofinalojacarroscombasedados;

public class JFrameMenu extends javax.swing.JFrame {

    public JFrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonInserirDono = new javax.swing.JButton();
        jButtonListarDonos = new javax.swing.JButton();
        jButtonInserirRaca = new javax.swing.JButton();
        jButtonListarRacas = new javax.swing.JButton();
        jButtonInserirPeer = new javax.swing.JButton();
        jButtonListarPets = new javax.swing.JButton();
        jButtonInserirPreco = new javax.swing.JButton();
        jButtonListarPrecos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jButtonInserirDono.setBackground(new java.awt.Color(204, 255, 255));
        jButtonInserirDono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonInserirDono.setText("Inserir Carro");
        jButtonInserirDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirDonoActionPerformed(evt);
            }
        });

        jButtonListarDonos.setBackground(new java.awt.Color(255, 153, 51));
        jButtonListarDonos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonListarDonos.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Manoel\\Programação_Disciplinas_IEFP\\Programacao_JAVA_UFCD0816\\ProjetoFinalLojaCarrosComBaseDados\\fogo.jpg")); // NOI18N
        jButtonListarDonos.setText("Conheça nosso estoque de carros");
        jButtonListarDonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarDonosActionPerformed(evt);
            }
        });

        jButtonInserirRaca.setBackground(new java.awt.Color(255, 255, 204));
        jButtonInserirRaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonInserirRaca.setText("Inserir Marca");
        jButtonInserirRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirRacaActionPerformed(evt);
            }
        });

        jButtonListarRacas.setBackground(new java.awt.Color(255, 255, 204));
        jButtonListarRacas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonListarRacas.setText("Listar Marcas");
        jButtonListarRacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarRacasActionPerformed(evt);
            }
        });

        jButtonInserirPeer.setBackground(new java.awt.Color(255, 153, 102));
        jButtonInserirPeer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonInserirPeer.setText("Inserir Modelo");
        jButtonInserirPeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirPeerActionPerformed(evt);
            }
        });

        jButtonListarPets.setBackground(new java.awt.Color(255, 153, 102));
        jButtonListarPets.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonListarPets.setText("Listar Modelos");
        jButtonListarPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPetsActionPerformed(evt);
            }
        });

        jButtonInserirPreco.setBackground(new java.awt.Color(204, 204, 255));
        jButtonInserirPreco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonInserirPreco.setText("Inserir Preço");
        jButtonInserirPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirPrecoActionPerformed(evt);
            }
        });

        jButtonListarPrecos.setBackground(new java.awt.Color(204, 204, 255));
        jButtonListarPrecos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonListarPrecos.setText("Listar Preços");
        jButtonListarPrecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPrecosActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Manoel\\Programação_Disciplinas_IEFP\\VB-NET_3934\\Projeto_Final-26-11-25\\Ex_Stand\\imagens\\focus.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\LogoLojaCarro2.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel3.setText("Automóveis de confiança !");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonInserirDono, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInserirRaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonListarRacas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonInserirPeer)
                            .addComponent(jButtonInserirPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonListarPets)
                            .addComponent(jButtonListarPrecos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jButtonListarDonos, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonInserirDono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonInserirRaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonListarRacas))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonInserirPeer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonListarPets)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonInserirPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonListarPrecos)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonListarDonos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirDonoActionPerformed
        JFrameInserirCarro jfil=new JFrameInserirCarro();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonInserirDonoActionPerformed

    private void jButtonListarDonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarDonosActionPerformed
        JFrameListarCarros jfil=new JFrameListarCarros();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonListarDonosActionPerformed

    private void jButtonInserirRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirRacaActionPerformed
        JFrameInserirMarca jfil=new JFrameInserirMarca();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonInserirRacaActionPerformed

    private void jButtonListarRacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarRacasActionPerformed
        JFrameListarMarcas jfil=new JFrameListarMarcas();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonListarRacasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButtonInserirPeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirPeerActionPerformed
       JFrameInserirModelo jfil=new JFrameInserirModelo();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonInserirPeerActionPerformed

    private void jButtonListarPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPetsActionPerformed
        JFrameListarModelos jfil=new JFrameListarModelos();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonListarPetsActionPerformed

    private void jButtonInserirPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirPrecoActionPerformed
        JFrameInserirPreco jfil=new JFrameInserirPreco();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonInserirPrecoActionPerformed

    private void jButtonListarPrecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPrecosActionPerformed
        JFrameListarPrecos jfil=new JFrameListarPrecos();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonListarPrecosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInserirDono;
    private javax.swing.JButton jButtonInserirPeer;
    private javax.swing.JButton jButtonInserirPreco;
    private javax.swing.JButton jButtonInserirRaca;
    private javax.swing.JButton jButtonListarDonos;
    private javax.swing.JButton jButtonListarPets;
    private javax.swing.JButton jButtonListarPrecos;
    private javax.swing.JButton jButtonListarRacas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
