/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfaceGrafica;


import Utentes.Utente;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author User
 */
public class JFrameListaUtentes extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListaUtentes
     */
    public JFrameListaUtentes() {
        initComponents();
        atualizarListaBD();
               
}   
   public void atualizarListaBD() {
    try {
        
         Class.forName("org.mariadb.jdbc.Driver");
         
        // XAMPP
        Connection SQlCnn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/utentes?user=root");
        System.out.println("Ligação com sucesso");
        
        Statement stat1 = SQlCnn.createStatement();
        
        // SQL Server   
        // ResultSet resultadoQuery = stat1.executeQuery("Select * From utentes.dbo.dadosutentes");   
        // XAMPP   
       ResultSet resultadoQuery = stat1.executeQuery("Select * From utentes.dadosutentes");   
        
        // Mysql   
        // ResultSet resultadoQuery = stat1.executeQuery("Select * From utentes.dadosutentes");

       String texto="";
   while(resultadoQuery.next()) 
          texto= texto + resultadoQuery.getString("niss")
                  + "\t"+ resultadoQuery.getString("Nome")
                  +"\n";
   jTextArea1.setText(texto);       
     //texto=texto.replaceAll("null","  ");
   SQlCnn.close();
        
    } catch (Exception ex) {
        jTextArea1.setText("Erro ao conectar com a base de dados: " + ex.getMessage());
        System.err.println("Erro BD: " + ex);
    }
}   
    
    
public void atualizarLista() {
        if (Utente.listaUtentes == null || Utente.listaUtentes.isEmpty()) {
            jTextArea1.setText("Nenhum utente cadastrado.");
            return;
        }
        
        StringBuilder texto = new StringBuilder();
        for (int i = 0; i < Utente.listaUtentes.size(); i++) {
            Utente utente = Utente.listaUtentes.get(i);
            texto.append(String.format("NISS: %.0f\n", utente.getNISS()));
            texto.append("Nome: ").append(utente.getNome()).append("\n");
            texto.append("Morada: ").append(utente.getMorada()).append("\n");
            texto.append("------------------------\n\n");
        }
        jTextArea1.setText(texto.toString());
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LISTA DE UTENTES");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListaUtentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListaUtentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListaUtentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListaUtentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new JFrameListaUtentes().setVisible(true);              
                
                }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
