algoritmo "SOMA NUMEROS 1 ATE 50 - USANDO ENQUANTO - V3"
// Função :    Demonstrar o uso da estrutura de repetição Enquanto

var
soma,contador: inteiro

inicio

 soma<-0
 contador <- 0
 enquanto contador <=50 faca

  soma<- soma + contador
  contador <- contador + 1       //desta forma, o ciclo é feito 51 vezes
  escreval(soma)
 fimenquanto
 escreva("A soma é: ",soma)
fimalgoritmo
