
package exemplo32_clinicaveterinariacombasedados;

/**
 *
 * @author User
 */
public class JFrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenu
     */
    public JFrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonInserirDono = new javax.swing.JButton();
        jButtonListarDonos = new javax.swing.JButton();
        jButtonInserirRaca = new javax.swing.JButton();
        jButtonListarRacas = new javax.swing.JButton();
        jButtonInserirPeer = new javax.swing.JButton();
        jButtonListarPets = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonInserirDono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonInserirDono.setText("Inserir dono");
        jButtonInserirDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirDonoActionPerformed(evt);
            }
        });

        jButtonListarDonos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonListarDonos.setText("Listar donos");
        jButtonListarDonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarDonosActionPerformed(evt);
            }
        });

        jButtonInserirRaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonInserirRaca.setText("Inserir Raça");
        jButtonInserirRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirRacaActionPerformed(evt);
            }
        });

        jButtonListarRacas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonListarRacas.setText("Listar Raças");
        jButtonListarRacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarRacasActionPerformed(evt);
            }
        });

        jButtonInserirPeer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonInserirPeer.setText("Inserir pet");
        jButtonInserirPeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirPeerActionPerformed(evt);
            }
        });

        jButtonListarPets.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonListarPets.setText("Listar pets");
        jButtonListarPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPetsActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("Inserir consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonInserirDono)
                    .addComponent(jButtonListarDonos)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonInserirRaca)
                        .addComponent(jButtonListarRacas)
                        .addComponent(jButtonInserirPeer)
                        .addComponent(jButtonListarPets)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButtonInserirDono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListarDonos)
                .addGap(62, 62, 62)
                .addComponent(jButtonInserirRaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListarRacas)
                .addGap(39, 39, 39)
                .addComponent(jButtonInserirPeer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListarPets)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirDonoActionPerformed
        JFrameInserirDono jfil=new JFrameInserirDono();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonInserirDonoActionPerformed

    private void jButtonListarDonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarDonosActionPerformed
        JFrameListarDonos jfil=new JFrameListarDonos();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonListarDonosActionPerformed

    private void jButtonInserirRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirRacaActionPerformed
        JFrameInserirRaca jfil=new JFrameInserirRaca();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonInserirRacaActionPerformed

    private void jButtonListarRacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarRacasActionPerformed
        JFrameListarRacas jfil=new JFrameListarRacas();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonListarRacasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButtonInserirPeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirPeerActionPerformed
       JFrameInserirPet jfil=new JFrameInserirPet();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonInserirPeerActionPerformed

    private void jButtonListarPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPetsActionPerformed
        JFrameListarPet jfil=new JFrameListarPet();
        jfil.setLocation(200,0);
        jfil.setVisible(true);
    }//GEN-LAST:event_jButtonListarPetsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonInserirDono;
    private javax.swing.JButton jButtonInserirPeer;
    private javax.swing.JButton jButtonInserirRaca;
    private javax.swing.JButton jButtonListarDonos;
    private javax.swing.JButton jButtonListarPets;
    private javax.swing.JButton jButtonListarRacas;
    // End of variables declaration//GEN-END:variables
}
